<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.library</groupId>
  <artifactId>BookMetroTicket</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>

  <dependencies>
    <!-- Servlet API -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>4.0.1</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>BookMetroTicket</finalName>

    <plugins>
      <!-- Compiler Plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>11</source>
          <target>11</target>
        </configuration>
      </plugin>

      <!-- WAR Plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.2</version>
      </plugin>

    </plugins>
  </build>

</project>

#lambda to dynamodb
import boto3
from uuid import uuid4
def lambda_handler(event, context):
    s3 = boto3.client("s3")
    dynamodb = boto3.resource('dynamodb')
    if 'Records' in event:
        for record in event['Records']:
            bucket_name = record['s3']['bucket']['name']
            object_key = record['s3']['object']['key']
            size = record['s3']['object'].get('size', -1)
            event_name = record.get('eventName', 'Unknown')
            event_time = record.get('eventTime', 'Unknown')
            dynamoTable = dynamodb.Table('newtable')
            dynamoTable.put_item(
                Item={
                    'unique': str(uuid4()),
                    'Bucket': bucket_name,
                    'Object': object_key,
                    'Size': size,
                    'Event': event_name,
                    'EventTime': event_time
                }
            )
    else:
        print("No Records key found in event")

//access policy -> s3 to sns
{ 
  "Version": "2008-10-17", 
  "Id": "__default_policy_ID", 
  "Statement": [ 
    { 
      "Sid": "__default_statement_ID", 
      "Effect": "Allow", 
      "Principal": { 
        "AWS": "*" 
 }, 
      "Action": [ 
        "SNS:Publish", 
        "SNS:RemovePermission", 
        "SNS:SetTopicAttributes", 
        "SNS:DeleteTopic", 
        "SNS:ListSubscriptionsByTopic", 
        "SNS:GetTopicAttributes", 
        "SNS:AddPermission", 
        "SNS:Subscribe" 
      ], 
      "Resource": "arn:aws:sns:us-east-1:352917280532:MyEmailTopic", 
      "Condition": { 
        "StringEquals": { 
          "AWS:SourceAccount": "352917280532" 
        } 
      } 
    }, 
    { 
      "Sid": "AllowS3Publish", 
      "Effect": "Allow", 
      "Principal": { 
        "Service": "s3.amazonaws.com"
   }, 
      "Action": "SNS:Publish", 
      "Resource": "arn:aws:sns:us-east-1:352917280532:MyEmailTopic", 
      "Condition": { 
        "ArnLike": { 
          "aws:SourceArn": "arn:aws:s3:::my-upload-bucket-2027-28" 
        }, 
        "StringEquals": { 
          "aws:SourceAccount": "352917280532" 
        } 
      } 
    } 
  ] 
} 

//sqs - access policy
{ 
  "Version": "2012-10-17", 
  "Id": "__default_policy_ID", 
  "Statement": [ 
    { 
      "Sid": "__owner_statement", 
         "Effect": "Allow",
  "Principal": { 
        "AWS": "arn:aws:iam::352917280532:root" 
      }, 
      "Action": "SQS:*", 
      "Resource": "arn:aws:sqs:us-east-1:352917280532:MyS3Queue" 
    }, 
    { 
      "Sid": "Allow-SNS-SendMessage", 
      "Effect": "Allow", 
      "Principal": { 
        "Service": "sns.amazonaws.com" 
      }, 
      "Action": "SQS:SendMessage", 
      "Resource": "arn:aws:sqs:us-east-1:352917280532:MyS3Queue", 
      "Condition": { 
        "ArnEquals": { 
          "aws:SourceArn": "arn:aws:sns:us-east-1:352917280532:MyS3SNSTopic" 
        } 
      } 
    } 
  ] 
}  

//sns-s3-sns-sqs-lambda
{ 
  "Version": "2012-10-17", 
  "Id": "__default_policy_ID", 
  "Statement": [ 
    { 
      "Sid": "__default_statement_ID", 
      "Effect": "Allow", 
      "Principal": { 
        "AWS": "*" 
      }, 
      "Action": [ 
        "SNS:Publish", 
        "SNS:RemovePermission", 
        "SNS:SetTopicAttributes", 
        "SNS:DeleteTopic", 
        "SNS:ListSubscriptionsByTopic", 
        "SNS:GetTopicAttributes", 
        "SNS:AddPermission", 
        "SNS:Subscribe" 
      ],
     "Resource": "arn:aws:sns:us-east-1:352917280532:MyS3SNSTopic",
Condition": { 
        "StringEquals": { 
          "AWS:SourceAccount": "352917280532" 
        } 
      } 
    }, 
    { 
      "Sid": "AllowS3Publish", 
      "Effect": "Allow", 
      "Principal": { 
 
        "Service": "s3.amazonaws.com" 
      }, 
      "Action": "SNS:Publish", 
      "Resource": "arn:aws:sns:us-east-1:352917280532:MyS3SNSTopic", 
      "Condition": { 
        "ArnLike": { 
          "aws:SourceArn": "arn:aws:s3:::mys3eventbucket1234salaar" 
        }, 
        "StringEquals": { 
          "aws:SourceAccount": "352917280532" 
        } 
      } 
    } 
  ] 
}

//lambda code for sqs
def lambda_handler(event, context): 
    for record in event['Records']: 
        print("Message received from SQS:") 
        print(record['body']) 
    return { 
        'statusCode': 200, 
        'body': 'Message processed successfully' 
    } 
